#ifndef COLORS_H
#define COLORS_H


#define F_COLOR_BLACK 0
#define F_COLOR_RED 1
#define F_COLOR_GREEN 2
#define F_COLOR_YELLOW 3
#define F_COLOR_BLUE 4
#define F_COLOR_MAGENTA 5
#define F_COLOR_CYAN 6
#define F_COLOR_WHITE 7
#define F_COLOR_LIGHT_BLACK 8
#define F_COLOR_LIGHT_RED 9
#define F_COLOR_LIGHT_GREEN 10
#define F_COLOR_LIGHT_YELLOW 11
#define F_COLOR_LIGHT_BLUE 12
#define F_COLOR_LIGHT_MAGENTA 13
#define F_COLOR_LIGHT_CYAN 14
#define F_COLOR_LIGHT_WHITE 15


#endif
