#ifndef colors_h
#define colors_h


#define F_COLOR_BLACK COLOR_BLACK
#define F_COLOR_RED COLOR_RED
#define F_COLOR_GREEN COLOR_GREEN
#define F_COLOR_YELLOW COLOR_YELLOW
#define F_COLOR_BLUE COLOR_BLUE
#define F_COLOR_MAGENTA COLOR_MAGENTA
#define F_COLOR_CYAN COLOR_CYAN
#define F_COLOR_WHITE COLOR_WHITE
#define F_COLOR_LIGHT_BLACK 8
#define F_COLOR_LIGHT_RED 9
#define F_COLOR_LIGHT_GREEN 10
#define F_COLOR_LIGHT_YELLOW 11
#define F_COLOR_LIGHT_BLUE 12
#define F_COLOR_LIGHT_MAGENTA 13
#define F_COLOR_LIGHT_CYAN 14
#define F_COLOR_LIGHT_WHITE 15


#endif