#ifndef ERRORS_H
#define ERRORS_H


#define ALL_GOOD 0
#define OBJ_NOT_FOUND 1
#define OBJ_ARRAY_IS_FULL 2
#define TOO_MANY_ITEMS_ON_TILE 3
#define NO_ITEMS_ON_TILE 4
#define TERMINAL_IS_TOO_SMALL 5
#define TILE_IS_OCCUPIED 6
#define FILE_NOT_FOUND 7
#define UI_LEVEL_IS_NULL 8
#define NOBODY_TO_POSSESS_ITEM 9
#define CREATURE_INVENTORY_IS_FULL 10
#define WIN_CROSSES_TERMINAL_BOUNDS 11



#endif
