#ifndef SETTINGS_H
#define SETTINGS_H

#include <curses.h>


#define MAX_ITEMS_ON_TILE 10


#define MAX_KEYS_IN_ONE 2 // maximum keys related to the same action

int KEY_MOVE_UP[MAX_KEYS_IN_ONE];
int KEY_MOVE_DOWN[MAX_KEYS_IN_ONE];
int KEY_MOVE_LEFT[MAX_KEYS_IN_ONE];
int KEY_MOVE_RIGHT[MAX_KEYS_IN_ONE];

int KEY_MOVE_UP_LEFT[MAX_KEYS_IN_ONE];
int KEY_MOVE_DOWN_LEFT[MAX_KEYS_IN_ONE];
int KEY_MOVE_DOWN_RIGHT[MAX_KEYS_IN_ONE];
int KEY_MOVE_UP_RIGHT[MAX_KEYS_IN_ONE];

int KEY_STAY[MAX_KEYS_IN_ONE];

int KEY_EXIT_GAME[MAX_KEYS_IN_ONE];

int KEY_WINRESIZE[MAX_KEYS_IN_ONE];


#endif
